import type { FamilyRole, Permission } from "./types";

export const defaultRolePermissions: Record<FamilyRole, Permission[]> = {
  owner: [
    "family:view",
    "family:create",
    "family:update",
    "family:delete",
    "member:view",
    "member:create",
    "member:update",
    "member:delete",
    "shared_fund:view",
    "shared_fund:create",
    "shared_fund:update",
    "shared_fund:delete",
    "shared_fund:manage_fund",
    "task:view",
    "task:create",
    "task:update",
    "task:delete",
    "task:review",
    "point_ledger:view",
    "point_ledger:adjust_points",
    "wish:view",
    "wish:create",
    "wish:update",
    "wish:delete",
    "report:view",
    "report:create",
    "report:update",
    "report:delete",
    "report:export"
  ],
  admin: [
    "family:view",
    "family:update",
    "member:view",
    "member:create",
    "member:update",
    "shared_fund:view",
    "shared_fund:create",
    "shared_fund:update",
    "shared_fund:manage_fund",
    "task:view",
    "task:create",
    "task:update",
    "task:review",
    "point_ledger:view",
    "point_ledger:adjust_points",
    "wish:view",
    "wish:create",
    "wish:update",
    "report:view",
    "report:create",
    "report:update"
  ],
  member: [
    "family:view",
    "member:view",
    "shared_fund:view",
    "task:view",
    "task:create",
    "wish:view",
    "wish:create",
    "report:view"
  ],
  child: ["family:view", "member:view", "task:view", "wish:view", "wish:create"],
  viewer: ["family:view", "member:view"]
};
